<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Actions' => 'Действия',
    'Active' => 'Активный',
    'Add Book' => 'Добавить книгу',
    'All' => 'Все',
    'Are you sure to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Book Listing' => 'Книга Листинг',
    'CSV' => 'CSV',
    'Clear selection' => 'Снять выделение',
    'Collapse' => 'Свернуть',
    'Collapse All' => 'Свернуть Все',
    'Comma Separated Values' => 'Значения, разделенные запятыми',
    'Delete' => 'Удалить',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Отключите все блокировщики всплывающих окон в вашем браузере, чтобы обеспечить надлежащее скачивание.',
    'Download Selected' => 'Скачать Избранные',
    'Excel' => 'Превосходить',
    'Expand' => 'Расширить',
    'Expand All' => 'Расширить Все',
    'Export' => 'Экспорт',
    'Export All Data' => 'Экспорт всех данных',
    'Export Page Data' => 'Экспорт данных страницы',
    'ExportWorksheet' => 'ExportWorksheet',
    'Generated' => 'Сгенерировано',
    'Generating the export file. Please wait...' => 'Создание файла для экспорта. Пожалуйста, подождите...',
    'Grid Export' => 'Экспорт грида',
    'HTML' => 'HTML',
    'Hyper Text Markup Language' => 'Язык Гипертекстовой Разметки',
    'Inactive' => 'Неактивный',
    'JSON' => 'JSON',
    'JavaScript Object Notation' => 'JavaScript Object Notation',
    'Library' => 'Библиотека',
    'Microsoft Excel 95+' => 'Microsoft Excel 95+',
    'No data found' => 'Нет данных',
    'Ok to proceed?' => 'Хорошо, чтобы продолжить?',
    'PDF' => 'PDF',
    'PDF export generated by kartik-v/yii2-grid extension' => 'Экспорт в формате PDF генерируется Kartik -V / расширения yii2',
    'Page' => 'Страница',
    'Portable Document Format' => 'Переносимый формат документа',
    'Request submitted! You may safely close this dialog after saving your downloaded file.' => 'Запрос , представленный ! Вы можете спокойно закрыть это диалоговое окно после сохранения загруженного файла.',
    'Reset Grid' => 'Сброс сетки',
    'Resize table columns just like a spreadsheet by dragging the column edges.' => 'Изменение размера столбцов таблицы как таблицы путем перетаскивания края столбцов.',
    'Show all data' => 'Показать все данные',
    'Show first page data' => 'Показать данные первой страницы',
    'Tab Delimited Text' => 'Таб ка разделитель текста',
    'Text' => 'Текст',
    'The CSV export file will be generated for download.' => 'Файл экспорта CSV будет создан для скачивания.',
    'The EXCEL export file will be generated for download.' => 'Файл экспорта EXCEL будет генерироваться для скачивания.',
    'The HTML export file will be generated for download.' => 'Файл экспорта HTML будут генерироваться для скачивания.',
    'The JSON export file will be generated for download.' => 'Файл экспорта JSON будет генерироваться для скачивания.',
    'The PDF export file will be generated for download.' => 'Файл в формате PDF экспорт будет генерироваться для скачивания.',
    'The TEXT export file will be generated for download.' => 'Файл экспорта текста будет создан для скачивания.',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => 'Страница сводки отображает сумму за первые 3 Количество колонок и AVG дляпоследнего.',
    'The table header sticks to the top in this demo as you scroll' => 'Заголовок таблицы прилипает к верхней в этой демо , как вы выделите',
    'Update' => 'Обновление',
    'View' => 'Просмотр',
    'Yii2 Grid Export (PDF)' => 'Yii2 Сетка Экспорт (в формате PDF)',
    'export' => 'Экспорт',
    'grid-export' => 'Сетка-экспорт',
    'krajee, grid, export, yii2-grid, pdf' => 'krajee, сетки, экспорт, yii2 сетки, PDF',
    '© Krajee Yii2 Extensions' => '© Krajee Yii2 Расширения',
];
