<?php
/**
* Message translations.
*
* This file is automatically generated by 'yii translate' command.
* It contains the localizable messages extracted from source code.
* You may modify this file by translating the extracted messages.
*
* Each array element represents the translation (value) of a message (key).
* If the value is empty, the message is considered as not translated.
* Messages that no longer need translation will have their translations
* enclosed between a pair of '@@' marks.
*
* Message string can be used with plural forms format. Check i18n section
* of the guide for details.
*
* NOTE: this file must be saved in UTF-8 encoding.
*/
return [
    'Append Line Break' => 'Добавьте обрыва линии',
    'Block Quote' => 'Блок Цитата',
    'Bold' => 'смелый',
    'Bulleted List' => 'маркированный список',
    'CTRL-Y' => 'CTRL -Y',
    'CTRL-Z' => 'CTRL -Z',
    'Code Block' => 'Код блок',
    'Definition List' => 'Список определений',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Отключите все блокировщики всплывающих окон в вашем браузере, чтобы обеспечить надлежащее скачать .',
    'Export' => 'экспорт',
    'Export content' => 'Экспорт содержимого',
    'Footnote' => 'сноска',
    'HTML' => 'HTML-',
    'Heading' => 'заголовок',
    'Heading {n}' => 'заголовок {n}',
    'Heading {n} Style' => 'заголовок {n} стиль',
    'Horizontal Line' => 'Горизонтальная Линия',
    'Image' => 'изображение',
    'Indent Text' => 'отступ',
    'Inline Code' => 'Встроенный код',
    'Italic' => 'курсив',
    'Loading Preview' => 'Загрузка Предпросмотр',
    'Markdown Export{line} *Generated {date} by {class}' => 'уценки Экспорт {line} * Генерируется {date} по {class}',
    'No content to display' => 'Нет содержания для отображения',
    'Numbered List' => 'Нумерованный список',
    'PHP Markdown Extra' => 'PHP Markdown Extra',
    'PHP SmartyPants Typographer' => 'PHP SmartyPants Typographer',
    'Paragraph' => 'пункт',
    'Preview' => 'предварительный просмотр',
    'Preview formatted text' => 'Предварительный форматированный текст',
    'Save as HTML' => 'Сохранить как HTML',
    'Save as text' => 'Сохранить в виде текста',
    'Text' => 'текст',
    'Toggle full screen' => 'Переключить на полный экран',
    'URL/Link' => 'URL / Ссылка',
    'Unindent Text' => 'Unindent Текст',
    'and' => 'и',
    'markdown-export' => 'уценки -экспорт',
    '{bullet} To undo / redo, press {keys}. You can also undo most button actions by clicking it again.' => '{bullet} Чтобы отменить / повторить , нажмите {keys} , Вы также можете отменить большинство действий , нажав кнопку еще раз .',
    '{bullet} You may use {link} syntax.' => '{bullet} Вы можете использовать {link} Синтаксис .',
];