<?= $this->registerCss('
body:after {
    content: "beta";
    position: absolute;
    width: 46px;
    height: 19px;
    background: #cc006a;
    top: 0px;
    left: -13px;
    text-align: center;
    font-size: 9px;
    font-family: sans-serif;
    text-transform: uppercase;
    font-weight: bold;
    color: #fff;
    line-height: 22px;
    -ms-transform: rotate(-45deg);
    -webkit-transform: rotate(-45deg);
    transform: rotate(-45deg);
    z-index: 9999;
}
') ?>